### ISSUE TITLE
python/t10001-resourcegraph.py test fails outside of flux environment

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-sched#1172]
Problem: when running `make check` on my Ubuntu desktop, this test fails for me, unless I run it in flux instance or via the `flux(1)` command front end.

```
      Start 92: python/t10001-resourcegraph.py
92/92 Test #92: python/t10001-resourcegraph.py ........***Failed    0.07 sec
Traceback (most recent call last):
  File "/home/garlick/proj/flux-sched/t/python/t10001-resourcegraph.py", line 22, in <module>
    from fluxion.resourcegraph.V1 import (
  File "/home/garlick/proj/flux-sched/src/python/fluxion/resourcegraph/V1.py", line 13, in <module>
    from flux.idset import IDset
ModuleNotFoundError: No module named 'flux'
```

**Comment by garlick** [comment]
I'm still seeing this failure on current master.
