### ISSUE TITLE
The latest msg watcher rework broke flux-sched

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#72]
This is just to see if anyone is working on a PR. If not, I can fix this part of the current jsc test case bug fixing work.

**Comment by dongahn** [comment]
```
make[1]: Entering directory `/nfs/tmp2/dahn/FLUXDEV/flux-sched/sched'
cc -g -Wall -Werror -Wno-error=deprecated-declarations -fPIC -D_GNU_SOURCE=1 -I/nfs/tmp2/dahn/FLUXDEV/flux-core -I/nfs/tmp2/dahn/FLUXDEV/flux-core/src/include -I/usr/include/czmq -I/usr/include/json-c   -I/usr/include/czmq  -I..//resrc   -c -o schedsrv.o schedsrv.c
schedsrv.c:59: error: expected declaration specifiers or '...' before 'flux_msg_watcher_t'
schedsrv.c: In function 'fill_resource_req':
schedsrv.c:158: warning: 'jsc_query_jcb_obj' is deprecated (declared at /nfs/tmp2/dahn/FLUXDEV/flux-core/src/modules/libjsc/jstatctl.h:107)
schedsrv.c: In function 'update_state':
schedsrv.c:184: warning: 'jsc_update_jcb_obj' is deprecated (declared at /nfs/tmp2/dahn/FLUXDEV/flux-core/src/modules/libjsc/jstatctl.h:119)
schedsrv.c: At top level:
```

This is the error message.

**Comment by garlick** [comment]
Oh I'm sorry!  I knew I needed to submit a PR to flux-sched and completely dropped the ball.  I will do it first thing tomorrow morning.

**Comment by dongahn** [comment]
Don't worry about it, @garlick. Thank you for the fix in advance.

**Comment by garlick** [comment]
After fixing the compliation problems, I am seeing a segfault in the sched tests that look like a problem introduced to flux-core in the latest reactor changes, though I can't seem to trigger it by loading and unloading other modules.  This needs further investigation.
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00002b5b3ad048a6 in ev_prepare_stop (loop=0x2b5b58014510, 
    w=0x2b5b58014dc0) at ev.c:4425
4425	    prepares [active - 1] = prepares [--preparecnt];
Traceback (most recent call last):
  File "/usr/share/gdb/auto-load/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19-gdb.py", line 63, in <module>
    from libstdcxx.v6.printers import register_libstdcxx_printers
ImportError: No module named 'libstdcxx'
(gdb) bt
#0  0x00002b5b3ad048a6 in ev_prepare_stop (loop=0x2b5b58014510, 
    w=0x2b5b58014dc0) at ev.c:4425
#1  0x00002b5b3aceeef5 in ev_flux_stop (loop=0x2b5b58014510, w=0x2b5b58014d90)
    at ev_flux.c:99
#2  0x00002b5b3ace6e7b in flux_watcher_destroy (w=0x2b5b58014e50)
    at reactor.c:194
#3  0x00002b5b3ace747d in dispatch_destroy (arg=0x2b5b58014ce0)
    at dispatch.c:70
#4  0x00002b5b3b39cfc2 in s_item_destroy (self=0x2b5b5800d2b0, 
    item=0x2b5b58014ea0, hard=<optimized out>) at src/zhash.c:137
#5  0x00002b5b3b39d064 in zhash_destroy (self_p=self_p@entry=0x2b5b5800d4d0)
    at src/zhash.c:101
#6  0x00002b5b3ace58af in flux_handle_destroy (hp=hp@entry=0x2b5b51caee18)
    at handle.c:216
#7  0x00002b5b3ace5923 in flux_close (h=0x2b5b5800d4a0) at handle.c:192
#8  0x000000000040c772 in module_thread (arg=0x17be670) at module.c:148
#9  0x00002b5b3b85d182 in start_thread (arg=0x2b5b51caf700)
    at pthread_create.c:312
#10 0x00002b5b3bf7947d in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb) quit
```
It looks like the module teardown that is closing the handle is destroying the handle watcher belonging to the dispatcher after the reactor has been destroyed?

**Comment by garlick** [comment]
Ah possibly why this is only now seen in sched is that the message handlers are not all unregistered when the sched module main returns.  That's a memory leak in sched, but core shouldn't segfault.  Probably in core I need to add a usecount for the reactor to defer its destruction until all watchers are stopped.
